version: '3'
services:
    redis:
      container_name: redis
      image: "redis:alpine"
      expose:
        - "6379"
      logging:
        driver: gelf
        options:
          gelf-address: "udp://localhost:12201"
          tag: "redis"
    mongo:
      image: mongo:4.2
      networks:
        - graylog
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
      environment:
        - http.host=0.0.0.0
        - transport.host=localhost
        - network.host=0.0.0.0
        - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      deploy:
        resources:
          limits:
            memory: 1g
      networks:
        - graylog
    graylog:
      image: graylog/graylog:4.2
      environment:
        - root_timezone=Europe/Paris
        - GRAYLOG_PASSWORD_SECRET=z07d2eiJQ1ZAaO3qZMn8sBRyRq8uBCKa7Yfl1ZZpKHVjBIQmKVQKxNKCKi6grgeQtUzbNLhtrZr4tMkeFTzShUD317oE64Fg
        # username: admin | Password: projetDevops
        - GRAYLOG_ROOT_PASSWORD_SHA2=bda1e3e2cccf60e986d713a14c82ae612a9d080a8810ab901d408b53b9f8ee8d
        - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
      networks:
        - graylog
      restart: always
      depends_on:
        - mongo
        - elasticsearch
      ports:
        # Graylog web interface and REST API
        - 9000:9000
        # Syslog TCP
        - 1514:1514
        # Syslog UDP
        - 1514:1514/udp
        # GELF TCP
        - 12201:12201
        # GELF UDP
        - 12201:12201/udp
networks:
    graylog:
      driver: bridge
